import React from 'react';
import { CheckCircle2, ExternalLink, Handshake, Leaf, Recycle, Scale, ShieldCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';

const contactEmail = 'enterprise@zigoservices.com';

function PolicyShell({ eyebrow, title, summary, effective, review, highlights, children, aside }) {
  return (
    <div className="bg-[#fbfaf8]">
      <header className="relative overflow-hidden border-b border-[#ECD5AB]/60 bg-gray-950 text-white">
        <div className="absolute -left-32 -top-48 h-96 w-96 rounded-full bg-[#7D582E]/30 blur-3xl" />
        <div className="absolute -right-20 top-0 h-80 w-80 rounded-full bg-[#ECD5AB]/10 blur-3xl" />
        <div className="relative mx-auto max-w-6xl px-6 py-16 lg:px-8 lg:py-24">
          <Link to="/" className="mb-9 inline-flex text-sm text-gray-300 transition-colors hover:text-[#ECD5AB]">← Back to Zigo Business</Link>
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#ECD5AB]">{eyebrow}</p>
          <h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-tight md:text-6xl">{title}</h1>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-gray-300">{summary}</p>
          <dl className="mt-8 flex flex-wrap gap-x-8 gap-y-3 text-sm text-gray-400">
            <div><dt className="inline font-semibold text-gray-200">Effective: </dt><dd className="inline">{effective}</dd></div>
            <div><dt className="inline font-semibold text-gray-200">Owner: </dt><dd className="inline">Management, Zigo Business Solutions Ltd</dd></div>
            <div><dt className="inline font-semibold text-gray-200">Review: </dt><dd className="inline">{review}</dd></div>
          </dl>
        </div>
      </header>

      {highlights && <section className="mx-auto max-w-6xl px-6 py-10 lg:px-8"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{highlights}</div></section>}

      <div className="mx-auto grid max-w-6xl gap-12 px-6 py-14 lg:grid-cols-[minmax(0,1fr)_280px] lg:px-8 lg:py-20">
        <article className="policy-copy space-y-12 text-[15px] leading-7 text-gray-700">{children}</article>
        <aside className="h-fit space-y-5 lg:sticky lg:top-28">{aside}</aside>
      </div>
    </div>
  );
}

function Section({ number, title, children }) {
  return <section><h2 className="text-2xl font-semibold text-gray-950">{number}. {title}</h2><div className="mt-4 space-y-4">{children}</div></section>;
}

function Checks({ items }) {
  return <ul className="space-y-3">{items.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#7D582E]" /><span>{item}</span></li>)}</ul>;
}

function Card({ icon: Icon, title, children }) {
  return <div className="rounded-2xl border border-[#ECD5AB]/70 bg-white p-6 shadow-sm"><Icon className="h-5 w-5 text-[#7D582E]" /><h2 className="mt-3 font-semibold text-gray-950">{title}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{children}</p></div>;
}

export function EnvironmentalPolicy() {
  return (
    <PolicyShell
      eyebrow="Corporate governance"
      title="Corporate Environmental Policy"
      summary="Our commitment to responsible resource use, pollution prevention, lawful waste management and sustainable technology practices."
      effective="24 August 2026"
      review="At least annually"
      highlights={[
        <Card key="resources" icon={Leaf} title="Use resources responsibly">Reduce avoidable energy, paper, water and material consumption across our workplaces and digital operations.</Card>,
        <Card key="technology" icon={Recycle} title="Manage technology responsibly">Extend equipment life and use authorised, environmentally sound channels for electronic waste and batteries.</Card>,
        <Card key="systems" icon={ShieldCheck} title="Build accountable systems">Set objectives, monitor performance, maintain evidence and correct environmental non-conformities promptly.</Card>,
        <Card key="improvement" icon={CheckCircle2} title="Improve continuously">Review performance and strengthen practical controls as our operations, evidence and obligations evolve.</Card>,
      ]}
      aside={<>
        <Card icon={Leaf} title="Policy contact">Report environmental concerns in good faith to <a className="font-medium text-[#7D582E] underline" href={`mailto:${contactEmail}?subject=Environmental%20concern`}>{contactEmail}</a>. Retaliation for a genuine report is not permitted.</Card>
        <div className="rounded-2xl border border-[#ECD5AB]/70 bg-[#f4ead9] p-6 text-sm leading-6 text-gray-700"><h2 className="font-semibold text-gray-950">Primary references</h2><div className="mt-3 space-y-3"><a className="flex gap-2 hover:text-[#7D582E]" href="https://nesrea.gov.ng/laws-regulations/" target="_blank" rel="noopener noreferrer">NESREA laws and regulations <ExternalLink className="mt-1 h-3 w-3" /></a><a className="flex gap-2 hover:text-[#7D582E]" href="https://climatecouncil.gov.ng/" target="_blank" rel="noopener noreferrer">Nigeria National Council on Climate Change <ExternalLink className="mt-1 h-3 w-3" /></a><a className="flex gap-2 hover:text-[#7D582E]" href="https://www.iso.org/standard/14001" target="_blank" rel="noopener noreferrer">ISO 14001 <ExternalLink className="mt-1 h-3 w-3" /></a><a className="flex gap-2 hover:text-[#7D582E]" href="https://www.un.org/sustainabledevelopment/sustainable-development-goals/" target="_blank" rel="noopener noreferrer">UN Sustainable Development Goals <ExternalLink className="mt-1 h-3 w-3" /></a></div></div>
      </>}
    >
      <Section number="1" title="Purpose and scope"><p>Zigo Business Solutions Ltd recognises that responsible environmental management is part of sustainable, resilient business. This policy applies to our directors, employees, contractors, workplaces, procurement, technology assets, digital services and activities that we control or can reasonably influence.</p><p>As a data, artificial intelligence, software and digital-transformation company, our direct footprint is different from that of a heavy industrial operator. Our material impacts may nevertheless include electricity and cloud-computing use, business travel, procurement, packaging, office waste, batteries and end-of-life electrical or electronic equipment.</p></Section>
      <Section number="2" title="Our commitments"><p>Within the scale and context of our operations, we commit to:</p><Checks items={["meet applicable Nigerian environmental laws, permits, regulatory directions and other compliance obligations relevant to our activities;","prevent pollution and avoid improper disposal, open burning or uncontrolled release of waste;","use energy, water, paper, equipment and digital infrastructure efficiently;","apply a life-cycle perspective when purchasing, operating, maintaining, reusing and disposing of technology;","set proportionate environmental objectives and review performance regularly; and","continually improve our environmental practices and controls."]} /></Section>
      <Section number="3" title="Resource-efficient and sustainable technology"><p>We will favour digital-first workflows, reduce unnecessary printing, apply practical energy-saving settings and avoid unnecessary processing, storage and infrastructure consumption. Product and engineering teams will consider efficient architecture, workload sizing, data retention and responsible use of AI and cloud resources when these choices can materially reduce environmental impact without compromising security, reliability or customer requirements.</p><p>Where feasible, we will monitor significant sources of energy and resource use, establish baselines and select improvement measures that are credible, measurable and proportionate to available data.</p></Section>
      <Section number="4" title="Electronic waste, batteries and other waste"><p>Equipment will be maintained, repaired, redeployed or reused where safe and practical before replacement. Obsolete electrical and electronic equipment, batteries and any hazardous components will be segregated from general waste, stored safely and transferred only through authorised collectors, recyclers or disposal channels where required. We will retain reasonable transfer, collection or disposal records.</p><p>Employees and contractors must not dump, burn, dismantle or informally transfer company electronic waste or batteries. Suspected leaks, damage, unsafe storage or improper disposal must be reported promptly.</p></Section>
      <Section number="5" title="Procurement and third parties"><p>Relevant purchasing decisions will consider energy efficiency, durability, repairability, packaging, reuse, recyclability, take-back arrangements and responsible end-of-life management alongside quality, security, accessibility, functionality, cost and operational need.</p><p>Suppliers and contractors whose work creates material environmental risk may be required to demonstrate lawful waste handling, appropriate licences or approvals, competent personnel and records. Material or repeated failure to meet agreed environmental requirements may affect supplier selection or continuation.</p></Section>
      <Section number="6" title="Climate, travel and resilience"><p>We will encourage virtual collaboration where it is effective, plan necessary travel efficiently and consider lower-impact options where practical. Environmental and climate-related risks—including power disruption, flooding, heat and supply-chain interruption—will be considered where relevant to business continuity, facilities, technology operations and customer delivery.</p><p>We will not describe an activity, product or the company as “carbon neutral”, “net zero”, “green” or otherwise environmentally superior unless the claim has a defined scope, reliable evidence and appropriate approval.</p></Section>
      <Section number="7" title="Governance, competence and reporting"><p>Management is accountable for this policy and may appoint a responsible officer to maintain applicable obligations, objectives, records and review actions. Team leads are responsible for controls within their areas; workers and contractors must follow relevant procedures and report environmental concerns or incidents.</p><p>Relevant personnel will receive proportionate awareness or training. Environmental incidents, regulatory notices, unsafe waste handling and material non-conformities will be documented, escalated to management, investigated and corrected. Where notification to a regulator, landlord, customer, emergency service or other authority is legally required, the company will make or support that notification within the applicable period.</p><p>Concerns may be reported in good faith to <a className="text-[#7D582E] underline" href={`mailto:${contactEmail}?subject=Environmental%20concern`}>{contactEmail}</a>. Retaliation for a genuine report is not permitted.</p></Section>
      <Section number="8" title="Objectives, records and review"><p>Environmental objectives will be selected according to significant impacts, compliance obligations, business risks and available resources. Measures may include paper reduction, equipment reuse, authorised e-waste transfers, energy-efficiency actions, staff awareness or supplier due diligence. Where targets are published, their scope, baseline, period and method of measurement will be stated.</p><p>This policy and supporting controls will be reviewed at least annually and after a material operational change, significant incident or relevant legal development. Records will be retained for a period appropriate to the applicable obligation and business need. Corrective actions will be tracked to closure.</p></Section>
      <Section number="9" title="Framework alignment and status"><p>This policy is informed by Nigerian environmental law and policy and by internationally recognised principles including ISO 14001’s life-cycle, compliance and continual-improvement approach and the UN Sustainable Development Goals, particularly Goals 12 and 13. These references guide our approach; they do not create a claim that Zigo Business Solutions Ltd is certified, independently verified or fully conformant with any voluntary standard.</p><p>Nothing in this policy limits a stricter legal, contractual or site-specific duty. If this policy conflicts with an applicable requirement, the applicable requirement prevails.</p></Section>
      <section className="rounded-2xl border border-[#ECD5AB] bg-[#f4ead9] p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#7D582E]">Approval</p><p className="mt-3 font-semibold text-gray-950">Approved and adopted by Management, Zigo Business Solutions Ltd</p><p className="mt-1 text-sm text-gray-600">Effective 24 August 2026 · Version 1.0 · Next scheduled review: August 2027</p></section>
    </PolicyShell>
  );
}

export function SustainabilityStatement() {
  return (
    <PolicyShell
      eyebrow="Corporate governance"
      title="Corporate Sustainability & Responsible Business Statement"
      summary="How Zigo Business Solutions Ltd approaches environmental responsibility, human rights, ethical business, responsible technology and sustainable economic participation."
      effective="10 July 2026"
      review="At least annually"
      highlights={[
        <Card key="environment" icon={Leaf} title="Environmental responsibility">Efficient resource use, climate awareness, pollution prevention and responsible technology lifecycles.</Card>,
        <Card key="people" icon={Users} title="People and human rights">Fair, safe and dignified work, equal opportunity, inclusion and respect for lawful employee rights.</Card>,
        <Card key="ethics" icon={Scale} title="Ethical business">Transparent records, fair contracting and zero tolerance for bribery, fraud or improper inducements.</Card>,
        <Card key="technology" icon={ShieldCheck} title="Responsible technology">Secure, traceable and appropriately governed use of data, artificial intelligence and digital services.</Card>,
      ]}
      aside={<><Card icon={Handshake} title="Long-term value">Our aim is to create responsible value for customers, employees, partners, communities and society while minimising avoidable harm.</Card><div className="rounded-2xl border border-[#ECD5AB]/70 bg-[#f4ead9] p-6 text-sm"><h2 className="font-semibold text-gray-950">Related policies</h2><Link className="mt-3 block text-[#7D582E] underline" to="/environmental-policy">Corporate Environmental Policy</Link><a className="mt-3 block text-[#7D582E] underline" href={`mailto:${contactEmail}?subject=Responsible%20business%20concern`}>{contactEmail}</a></div></>}
    >
      <Section number="1" title="Purpose and scope"><p>Zigo Business Solutions Ltd recognises that sustainable business requires responsible management of environmental, social, economic and governance impacts. This Statement applies, as appropriate, to our management, employees, contractors, procurement, technology operations, projects and business relationships.</p><p>As a Nigerian provider of software, data, artificial intelligence, digital transformation, cybersecurity and related services, our decisions can affect employees, customers, suppliers, communities, the environment and the broader digital economy.</p></Section>
      <Section number="2" title="Our sustainability principles"><Checks items={["Comply with applicable Nigerian laws and regulatory requirements.","Respect internationally recognised human rights and promote fair, safe and dignified work.","Use resources responsibly and minimise avoidable environmental and social harm.","Conduct business ethically, transparently and without bribery or corruption.","Consider sustainability, security and lawful conduct in procurement and supplier relationships.","Protect personal information and promote responsible, inclusive technology.","Support Nigerian enterprise participation, skills and responsible economic development.","Improve continuously without making unsupported environmental or social claims."]} /></Section>
      <Section number="3" title="Environmental responsibility"><p>We integrate proportionate environmental considerations into operations and technology decisions. We favour digital-first processes, efficient energy and computing use, appropriate data retention, reduced printing and responsible purchasing. Equipment should be maintained, repaired, reused or redeployed before replacement where safe and practical.</p><p>Electronic equipment, batteries and other controlled waste must not be dumped, burned or transferred through inappropriate general-waste channels. We will use authorised or otherwise lawful collection, recycling and disposal arrangements where required and maintain reasonable evidence of transfer.</p><p>We consider climate-related risks and opportunities relevant to our operations, including energy efficiency, travel, cloud infrastructure, business continuity and avoidable emissions. Environmental claims must have a defined scope, reliable evidence and appropriate approval.</p></Section>
      <Section number="4" title="Human rights and responsible employment"><p>We support internationally recognised human rights and seek to avoid causing, contributing to or knowingly benefiting from abuse. We prohibit forced or involuntary labour, unlawful child labour, harassment, intimidation and unlawful discrimination.</p><p>Employment decisions should be based on legitimate considerations such as competence, qualifications, performance and organisational requirements. We support fair terms, agreed remuneration, lawful freedom of association, safe working conditions, employee well-being and meaningful participation by women and underrepresented groups.</p></Section>
      <Section number="5" title="Health, safety and well-being"><p>We maintain measures appropriate to technology and professional-services operations: safe workplaces, foreseeable-risk assessment, responsible electrical-equipment use, ergonomic practices, emergency arrangements and good-faith reporting of unsafe conditions. At client, industrial or field locations, applicable site and legal requirements must also be followed.</p></Section>
      <Section number="6" title="Ethical business and anti-corruption"><p>Zigo does not support bribery, corruption, fraud, extortion, kickbacks or improper inducements. Employees and representatives must not offer, request, give or accept an improper benefit intended to influence a business, procurement, regulatory or governmental decision.</p><p>We seek to maintain accurate records, disclose or avoid conflicts of interest, contract fairly, protect confidential information, cooperate with legitimate audits and take proportionate action where misconduct is suspected. Comparable standards are expected from suppliers and partners.</p></Section>
      <Section number="7" title="Responsible technology, AI and data"><p>We seek to comply with applicable Nigerian data-protection requirements, implement reasonable security safeguards and respect authorised use and customer ownership of information. We avoid unnecessary collection or retention and consider accessibility and inclusion in digital-service design.</p><p>AI solutions should be designed with appropriate accuracy, traceability, security, deterministic controls and responsible access. Consequential AI-assisted decisions should receive suitable human oversight, review and validation.</p></Section>
      <Section number="8" title="Sustainable procurement and supply chain"><p>Relevant supplier selection may consider compliance, quality, ethical conduct, labour practices, environmental responsibility, security, data protection, durability, packaging, energy efficiency, local participation and customer requirements. Serious non-compliance may result in corrective action, reassessment or termination.</p><p>Where proportionate, signed agreements should contain compliance duties, audit and recordkeeping rights, prompt incident notification, corrective-action requirements, remediation-cost allocation and appropriately drafted indemnities for regulatory breaches, unlawful conduct, data or security incidents, environmental harm and third-party claims. Indemnities require legal or contract-review approval.</p></Section>
      <Section number="9" title="Local enterprises and communities"><p>Where commercially appropriate, we consider qualified Nigerian SMEs, support local professional and technical talent, promote skills and knowledge transfer, provide fair supplier opportunities and pursue partnerships that strengthen local technological capacity. Our objective is to support growth that builds rather than unnecessarily displaces local capability.</p></Section>
      <Section number="10" title="Sustainable customer solutions"><p>We seek to help customers reduce inefficient manual processes through digital documentation, workflow automation, responsible cloud adoption, data-driven decisions, electronic collaboration, improved retrieval and maintainable infrastructure. Digitalisation is not automatically sustainable; cost, computing resources, security, accessibility and long-term maintenance remain important design considerations.</p></Section>
      <Section number="11" title="Governance and accountability"><p>Management owns this Statement and may delegate implementation as the Company grows. Reasonable evidence may include policy acknowledgements, training, procurement and disposal records, supplier assessments, project decisions, workplace actions and sustainability objectives.</p><p>Concerns may be raised in good faith with management or through <a className="text-[#7D582E] underline" href={`mailto:${contactEmail}?subject=Responsible%20business%20concern`}>{contactEmail}</a>. Retaliation for a genuine report is not permitted. Legitimate concerns will be reviewed and addressed proportionately.</p></Section>
      <Section number="12" title="Initial priorities"><p>Initial priorities include digital internal processes, reduced printing, efficient equipment settings, responsible handling of obsolete electronics, sustainability checks in significant procurement, fair employment, responsible data and AI governance, Nigerian SME participation and periodic identification of measurable improvements.</p></Section>
      <Section number="13" title="Framework alignment"><p>This Statement is informed, as applicable, by Nigeria’s Climate Change Act, National Policy on Environment, NESREA requirements, labour and employment law, anti-corruption legislation and the Nigeria Data Protection Act 2023. International reference points include the UN Sustainable Development Goals, UN Global Compact Ten Principles, UN Guiding Principles on Business and Human Rights, UN Supplier Code of Conduct and ILO fundamental principles and rights at work.</p></Section>
      <Section number="14" title="Status and legal effect"><p>This Statement does not represent ISO certification, UN Global Compact participation, endorsement by the UN, UNDP, NESREA or another organisation, or independently established performance unless separately documented.</p><p>It communicates the Company’s responsible-business commitments and does not create contractual rights, warranties, guarantees, indemnities or third-party causes of action. It does not limit or exclude any responsibility that cannot lawfully be limited or excluded. Applicable higher legal or contractual requirements prevail, and contractual indemnities must be contained in a separately executed agreement.</p></Section>
      <section className="rounded-2xl border border-[#ECD5AB] bg-[#f4ead9] p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#7D582E]">Management commitment</p><p className="mt-3 font-semibold text-gray-950">Approved and adopted by Management, Zigo Business Solutions Ltd</p><p className="mt-1 text-sm text-gray-600">Effective 10 July 2026 · Version 1.0 · Next scheduled review: July 2027</p></section>
    </PolicyShell>
  );
}
